(()=>{
'use strict';
const $=id=>document.getElementById(id);
const finite=v=>Number.isFinite(Number(v));
const css=`.conf-card{background:#111b2e;border:1px solid #26344d;border-radius:16px;padding:18px;grid-column:1/-1}.conf-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.conf-box{background:#0d1728;border:1px solid #26344d;border-radius:13px;padding:14px}.conf-head{display:flex;justify-content:space-between;align-items:center;gap:12px}.conf-title{font-weight:800}.conf-score{font-size:28px;font-weight:900}.conf-bull{color:#32c48d}.conf-bear{color:#ef6262}.conf-neutral{color:#e4b84b}.conf-rows{margin-top:10px}.conf-row{display:grid;grid-template-columns:1fr 58px 72px;gap:8px;padding:7px 0;border-bottom:1px solid #1b2940;align-items:center}.conf-row:last-child{border-bottom:0}.conf-factor{color:#c8d1df}.conf-signal{text-align:right;font-weight:700}.conf-pts{text-align:right;color:#91a0b7}.conf-note{color:#91a0b7;font-size:11px;line-height:1.5;margin-top:10px}.conf-bar{height:7px;background:#18263b;border-radius:8px;overflow:hidden;margin-top:8px}.conf-fill{height:100%;border-radius:8px}@media(max-width:850px){.conf-grid{grid-template-columns:1fr}}`;
function addStyles(){if($('confluenceStyles'))return;const s=document.createElement('style');s.id='confluenceStyles';s.textContent=css;document.head.appendChild(s)}
function ema(a,n){if(a.length<n)return null;const k=2/(n+1);let e=a.slice(0,n).reduce((x,y)=>x+y,0)/n;for(let i=n;i<a.length;i++)e=a[i]*k+e*(1-k);return e}
function rsi(a,n=14){if(a.length<=n)return null;let g=0,l=0;for(let i=1;i<=n;i++){const d=a[i]-a[i-1];g+=Math.max(d,0);l+=Math.max(-d,0)}let ag=g/n,al=l/n;for(let i=n+1;i<a.length;i++){const d=a[i]-a[i-1];ag=(ag*(n-1)+Math.max(d,0))/n;al=(al*(n-1)+Math.max(-d,0))/n}return al===0?100:100-100/(1+ag/al)}
function macd(rows){if(rows.length<35)return null;const c=rows.map(x=>x.close);const calc=n=>{const k=2/(n+1);let e=c.slice(0,n).reduce((a,b)=>a+b,0)/n,out=Array(n-1).fill(null);for(let i=n-1;i<c.length;i++){if(i===n-1)e=c.slice(0,n).reduce((a,b)=>a+b,0)/n;else e=c[i]*k+e*(1-k);out.push(e)}return out};const a12=calc(12),a26=calc(26),vals=[];let sig=null;for(let i=0;i<c.length;i++)if(a12[i]!=null&&a26[i]!=null){const v=a12[i]-a26[i];sig=sig==null?v:v*.2+sig*.8;vals.push({v,sig})}if(vals.length<2)return null;const x=vals.at(-1),p=vals.at(-2);return{bull:x.v>x.sig,bullCross:p.v<=p.sig&&x.v>x.sig,bearCross:p.v>=p.sig&&x.v<x.sig,spread:x.v-x.sig}}
function levels(rows){const r=rows.slice(-60);if(!r.length)return null;const p=r.at(-1).close,lows=r.map(x=>x.low).filter(x=>x<p),highs=r.map(x=>x.high).filter(x=>x>p);return{support:lows.length?Math.max(...lows):Math.min(...r.map(x=>x.low)),resistance:highs.length?Math.min(...highs):Math.max(...r.map(x=>x.high))}}
function direction(current,previous,lowerIsBull=true){if(!finite(current)||!finite(previous)||Number(current)===Number(previous))return 0;const rising=Number(current)>Number(previous);return lowerIsBull?(rising?-1:1):(rising?1:-1)}
function macroSignals(m){const out=[];const add=(name,current,previous,weight,lowerIsBull)=>{if(finite(current)&&finite(previous)&&Number(current)!==Number(previous))out.push({name,weight,signal:direction(current,previous,lowerIsBull)})};
add('Broad USD',m?.dxy?.value,m?.dxy?.previous,10,true);
add('Real yields',m?.realTenYear?.value,m?.realTenYear?.previous,10,true);
add('US 10Y',m?.tenYear?.value,m?.tenYear?.previous,6,true);
add('Core PCE trend',m?.corePce?.value,m?.corePce?.previous,6,true);
add('CPI trend',m?.cpi?.value,m?.cpi?.previous,4,true);
add('Core CPI trend',m?.coreCpi?.value,m?.coreCpi?.previous,4,true);
add('PCE trend',m?.pce?.value,m?.pce?.previous,3,true);
add('Fed rate',m?.fedEffective?.value,m?.fedEffective?.previous,3,true);
add('Unemployment',m?.unemployment?.value,m?.unemployment?.previous,2,false);
return out}
function technical(rows){const c=rows.map(x=>x.close),price=c.at(-1),e20=ema(c,20),e50=ema(c,50),e200=ema(c,200),rv=rsi(c),mc=macd(rows),lv=levels(rows),out=[];if(e20!=null&&e50!=null)out.push({name:'EMA trend',weight:14,signal:price>e20&&e20>e50?1:price<e20&&e20<e50?-1:0});if(e200!=null)out.push({name:'200 EMA',weight:8,signal:price>e200?1:-1});if(rv!=null)out.push({name:'RSI',weight:8,signal:rv>55?1:rv<45?-1:0});if(mc)out.push({name:'MACD',weight:12,signal:mc.bull?1:-1});if(lv){const nearR=Math.abs(lv.resistance-price)/price<.015,nearS=Math.abs(price-lv.support)/price<.015;out.push({name:'S/R position',weight:10,signal:nearS?1:nearR?-1:price>lv.resistance?1:price<lv.support?-1:0})}return out}
function score(rows,m){const factors=[...technical(rows),...macroSignals(m)];let total=0,weight=0;for(const f of factors){total+=f.signal*f.weight;weight+=f.weight}if(!weight)return null;const normalized=Math.round(50+(total/weight)*50);return{score:Math.max(0,Math.min(100,normalized)),factors,available:weight}}
function label(s){return s>=70?'Bullish':s<=30?'Bearish':'Neutral'}
function renderMetal(id,metal,rows,m){const r=score(rows,m),box=$(id);if(!box||!r)return;const cls=r.score>=70?'conf-bull':r.score<=30?'conf-bear':'conf-neutral';const sorted=r.factors.slice().sort((a,b)=>Math.abs(b.signal*b.weight)-Math.abs(a.signal*a.weight));box.innerHTML=`<div class="conf-head"><div><div class="conf-title">${metal==='gold'?'GOLD · XAU/USD':'SILVER · XAG/USD'}</div><div class="conf-score ${cls}">${r.score}/100 · ${label(r.score)}</div></div><div class="muted">${r.available} pts evaluated</div></div><div class="conf-bar"><div class="conf-fill ${cls}" style="width:${r.score}%"></div></div><div class="conf-rows">${sorted.map(f=>`<div class="conf-row"><div class="conf-factor">${f.name}</div><div class="conf-signal ${f.signal>0?'conf-bull':f.signal<0?'conf-bear':'conf-neutral'}">${f.signal>0?'Bull':f.signal<0?'Bear':'Neutral'}</div><div class="conf-pts">${f.signal===0?'0':(f.signal>0?'+':'−')+f.weight}</div></div>`).join('')}</div><div class="conf-note">Macro factors are scored from their latest change versus the prior reported observation. NFP is displayed but excluded because no consensus/surprise series is available. Missing data is excluded rather than guessed.</div>`}
async function run(){addStyles();if($('confluenceCard'))return;const grid=document.querySelector('.grid');if(!grid)return;const card=document.createElement('section');card.id='confluenceCard';card.className='conf-card';card.innerHTML='<div class="section">Confluence Score</div><div class="conf-grid"><div id="confGold" class="conf-box">Loading Gold analysis…</div><div id="confSilver" class="conf-box">Loading Silver analysis…</div></div><div class="conf-note">Confluence is a rule-based summary of the dashboard’s technical and macro signals. It is not a prediction or trading instruction.</div>';grid.appendChild(card);try{const [hr,mr]=await Promise.all([fetch('/api/history',{cache:'no-store'}),fetch('/api/macro',{cache:'no-store'})]);const hd=await hr.json(),md=await mr.json();const normalize=d=>{const o={gold:[],silver:[]},rates=d?.rates||d?.data?.rates||{};for(const [date,x] of Object.entries(rates))for(const [sym,k] of [['XAU','gold'],['XAG','silver']])if(x?.[sym])o[k].push({time:date,open:+x[sym].open,high:+x[sym].high,low:+x[sym].low,close:+x[sym].close});o.gold.sort((a,b)=>a.time.localeCompare(b.time));o.silver.sort((a,b)=>a.time.localeCompare(b.time));return o};const h=normalize(hd),m=md?.data||{};renderMetal('confGold','gold',h.gold,m);renderMetal('confSilver','silver',h.silver,m)}catch(e){card.querySelector('.conf-grid').innerHTML='<div class="conf-box">Confluence unavailable — existing dashboard remains unaffected.</div>'}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();
(()=>{const add=()=>{const wrap=[...document.querySelectorAll('.buttons')].find(x=>x.querySelector('[data-days="30"]'));if(!wrap||wrap.querySelector('[data-days="1"]'))return;const b=document.createElement('button');b.textContent='1D';b.dataset.days='1';wrap.insertBefore(b,wrap.firstElementChild);b.onclick=()=>{wrap.querySelectorAll('[data-days]').forEach(x=>x.classList.remove('active'));b.classList.add('active');days=1;if(series){series.setData(visible());chart.timeScale().fitContent()}};const n=document.createElement('div');n.className='muted';n.style.marginTop='6px';n.textContent='Chart candles are daily. 1D/1M/3M/6M/1Y are lookback periods; EMA 20/50/200 is correctly calculated on the full daily history, so it should not change when only the lookback changes.';wrap.parentElement.appendChild(n)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(add,0));else setTimeout(add,0)})();
})();