(()=>{
'use strict';
const $=id=>document.getElementById(id);
let history={gold:[],silver:[]}, selected='gold', days=90, overlayChart=null, overlayWrap=null;
const fmt=v=>Number.isFinite(Number(v))?Number(v).toLocaleString(undefined,{maximumFractionDigits:2}):'—';
function ema(a,n){if(a.length<n)return null;let k=2/(n+1),e=a.slice(0,n).reduce((x,y)=>x+y,0)/n;for(let i=n;i<a.length;i++)e=a[i]*k+e*(1-k);return e}
function rsi(a,n=14){if(a.length<=n)return null;let g=0,l=0;for(let i=1;i<=n;i++){let d=a[i]-a[i-1];g+=Math.max(d,0);l+=Math.max(-d,0)}let ag=g/n,al=l/n;for(let i=n+1;i<a.length;i++){let d=a[i]-a[i-1];ag=(ag*(n-1)+Math.max(d,0))/n;al=(al*(n-1)+Math.max(-d,0))/n}return al?100-100/(1+ag/al):100}
function normalize(d){const out={gold:[],silver:[]},rates=d?.rates||d?.data?.rates||{};for(const [date,x] of Object.entries(rates))for(const [sym,key] of [['XAU','gold'],['XAG','silver']])if(x?.[sym])out[key].push({time:date,open:+x[sym].open,high:+x[sym].high,low:+x[sym].low,close:+x[sym].close});out.gold.sort((a,b)=>a.time.localeCompare(b.time));out.silver.sort((a,b)=>a.time.localeCompare(b.time));return out}
function visible(){return (history[selected]||[]).slice(-days)}
function levels(rows){if(!rows.length)return null;const r=rows.slice(-Math.min(60,rows.length));return{support:Math.min(...r.map(x=>x.low)),resistance:Math.max(...r.map(x=>x.high))}}
function addStyles(){if($('dashExtraStyles'))return;const s=document.createElement('style');s.id='dashExtraStyles';s.textContent='.dash-extra{background:#111b2e;border:1px solid #26344d;border-radius:16px;padding:18px;grid-column:1/-1}.dash-extra-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}.dash-extra-box{background:#0d1728;border:1px solid #26344d;border-radius:10px;padding:11px}.dash-extra-box span{display:block;color:#91a0b7;font-size:10px}.dash-extra-box b{display:block;margin-top:5px}.dash-note{color:#91a0b7;font-size:11px;line-height:1.5;margin-top:10px}@media(max-width:850px){.dash-extra-grid{grid-template-columns:repeat(2,1fr)}}';document.head.appendChild(s)}
function insert(id,title,html,afterId){if($(id))return;const c=document.createElement('section');c.id=id;c.className='dash-extra';c.innerHTML='<div class="section">'+title+'</div>'+html;const a=$(afterId),t=a&&a.closest?a.closest('section.card'):a;if(t?.parentNode)t.parentNode.insertBefore(c,t.nextSibling);else document.querySelector('.grid')?.appendChild(c)}
function buildPanels(){addStyles();if(!$('dashUpdated')){const st=$('status');if(st){const e=document.createElement('div');e.id='dashUpdated';e.className='muted';e.style.marginTop='4px';e.textContent='Prices last updated: —';st.parentNode.appendChild(e)}}
insert('dashPriceIntel','Price Intelligence','<div class="dash-extra-grid"><div class="dash-extra-box"><span>Gold current</span><b id="xGold">—</b></div><div class="dash-extra-box"><span>Gold 24h</span><b id="xGoldCh">—</b></div><div class="dash-extra-box"><span>Silver current</span><b id="xSilver">—</b></div><div class="dash-extra-box"><span>Silver 24h</span><b id="xSilverCh">—</b></div><div class="dash-extra-box"><span>Gold / Silver ratio</span><b id="xRatio">—</b></div><div class="dash-extra-box"><span>Gold 30D</span><b id="xGold30">—</b></div><div class="dash-extra-box"><span>Silver 30D</span><b id="xSilver30">—</b></div><div class="dash-extra-box"><span>Relative strength</span><b id="xLeader">—</b></div></div><div class="dash-note">30-day performance is calculated from the available daily historical candles.</div>','gold');
insert('dashTech','Technical Decision Layer','<div class="dash-extra-grid"><div class="dash-extra-box"><span>Gold trend</span><b id="xGT">—</b></div><div class="dash-extra-box"><span>Silver trend</span><b id="xST">—</b></div><div class="dash-extra-box"><span>Gold RSI</span><b id="xGR">—</b></div><div class="dash-extra-box"><span>Silver RSI</span><b id="xSR">—</b></div><div class="dash-extra-box"><span>Gold support</span><b id="xGS">—</b></div><div class="dash-extra-box"><span>Gold resistance</span><b id="xGRs">—</b></div><div class="dash-extra-box"><span>Silver support</span><b id="xSS">—</b></div><div class="dash-extra-box"><span>Silver resistance</span><b id="xSRs">—</b></div></div><div class="dash-note" id="xTechNote">Waiting for data.</div>','chart');
insert('dashPatterns','Pattern Recognition & Impact','<div class="dash-extra-grid"><div class="dash-extra-box"><span>Gold pattern</span><b id="xGP">—</b></div><div class="dash-extra-box"><span>Gold impact</span><b id="xGI">—</b></div><div class="dash-extra-box"><span>Silver pattern</span><b id="xSP">—</b></div><div class="dash-extra-box"><span>Silver impact</span><b id="xSI">—</b></div></div><div class="dash-note">Patterns are calculated from the latest daily candles. They indicate probability, not certainty.</div>','dashTech');
insert('dashRegime','Market Regime','<div class="dash-extra-grid"><div class="dash-extra-box"><span>Gold</span><b id="xGReg">—</b></div><div class="dash-extra-box"><span>Silver</span><b id="xSReg">—</b></div><div class="dash-extra-box"><span>Dollar backdrop</span><b id="xDollar">—</b></div><div class="dash-extra-box"><span>Macro backdrop</span><b id="xMacro">—</b></div></div><div class="dash-note" id="xRegNote">Waiting for macro data.</div>','dashPatterns');}
function updatePanels(){for(const [k,p] of Object.entries(history)){if(!p.length)continue;const c=p.map(x=>x.close),lv=levels(p),t=ema(c,20),e=ema(c,50),rr=rsi(c),q=k==='gold'?'x':'x';if($(k==='gold'?'xGT':'xST'))$(k==='gold'?'xGT':'xST').textContent=t&&e?(c.at(-1)>t&&t>e?'Bull Trend':c.at(-1)<t&&t<e?'Bear Trend':'Mixed'):'Insufficient data';if($(k==='gold'?'xGR':'xSR'))$(k==='gold'?'xGR':'xSR').textContent=rr==null?'—':rr.toFixed(1);if(lv){$(k==='gold'?'xGS':'xSS').textContent=fmt(lv.support);$(k==='gold'?'xGRs':'xSRs').textContent=fmt(lv.resistance)}if(k==='gold'){$('xGold30')&&($('xGold30').textContent=c.length>30?(((c.at(-1)/c.at(-31))-1)*100).toFixed(2)+'%':'—');$('xGold')&&($('xGold').textContent=fmt(c.at(-1)))}else{$('xSilver30')&&($('xSilver30').textContent=c.length>30?(((c.at(-1)/c.at(-31))-1)*100).toFixed(2)+'%':'—');$('xSilver')&&($('xSilver').textContent=fmt(c.at(-1)))}}if(history.gold.length&&history.silver.length){const g=history.gold.at(-1).close,s=history.silver.at(-1).close;if($('xRatio'))$('xRatio').textContent=fmt(g/s);if($('xLeader'))$('xLeader').textContent='Gold/Silver comparison updated'}}
function cleanup(){if(overlayChart){try{overlayChart.remove()}catch(e){}}overlayChart=null;if(overlayWrap){overlayWrap.remove();overlayWrap=null}}
function drawOverlay(){const host=$('chart'),rows=visible();if(!host||!rows.length||!window.LightweightCharts)return;const lv=levels(rows);if(!lv)return;cleanup();if(getComputedStyle(host).position==='static')host.style.position='relative';overlayWrap=document.createElement('div');overlayWrap.id='srOverlay';Object.assign(overlayWrap.style,{position:'absolute',inset:'0',pointerEvents:'none',zIndex:'3'});host.appendChild(overlayWrap);overlayChart=LightweightCharts.createChart(overlayWrap,{layout:{background:{color:'transparent'},textColor:'transparent'},grid:{vertLines:{visible:false},horzLines:{visible:false}},rightPriceScale:{visible:false,borderVisible:false},leftPriceScale:{visible:false,borderVisible:false},timeScale:{visible:false,borderVisible:false,timeVisible:false,secondsVisible:false},handleScroll:false,handleScale:false,crosshair:{mode:0}});const hi=overlayChart.addLineSeries({lineVisible:false,lastValueVisible:false,priceLineVisible:false,crosshairMarkerVisible:false}),lo=overlayChart.addLineSeries({lineVisible:false,lastValueVisible:false,priceLineVisible:false,crosshairMarkerVisible:false});hi.setData(rows.map(x=>({time:x.time,value:x.high})));lo.setData(rows.map(x=>({time:x.time,value:x.low})));const s=overlayChart.addLineSeries({color:'#32c48d',lineWidth:2,lastValueVisible:false,priceLineVisible:false,crosshairMarkerVisible:false}),r=overlayChart.addLineSeries({color:'#ef6262',lineWidth:2,lastValueVisible:false,priceLineVisible:false,crosshairMarkerVisible:false});s.setData(rows.map(x=>({time:x.time,value:lv.support})));r.setData(rows.map(x=>({time:x.time,value:lv.resistance})));overlayChart.timeScale().fitContent()}
async function load(){try{const r=await fetch('/api/history',{cache:'no-store'}),d=await r.json();if(!r.ok||!d.success)return;history=normalize(d);updatePanels();setTimeout(drawOverlay,300)}catch(e){}}
function hook(){document.querySelectorAll('[data-metal]').forEach(b=>b.addEventListener('click',()=>{selected=b.dataset.metal;setTimeout(()=>{updatePanels();drawOverlay()},350)}));document.querySelectorAll('[data-days]').forEach(b=>b.addEventListener('click',()=>{days=+b.dataset.days;setTimeout(drawOverlay,350)}));window.addEventListener('resize',()=>overlayChart&&overlayWrap&&overlayChart.applyOptions({width:overlayWrap.clientWidth,height:overlayWrap.clientHeight}))}
function addLegend(){if($('srLegend'))return;const host=$('chart');if(!host)return;if(getComputedStyle(host).position==='static')host.style.position='relative';const el=document.createElement('div');el.id='srLegend';el.innerHTML='<span style="color:#32c48d">● Support</span>&nbsp;&nbsp;<span style="color:#ef6262">● Resistance</span>';Object.assign(el.style,{position:'absolute',left:'10px',top:'8px',zIndex:'5',fontSize:'11px',background:'rgba(7,16,28,.75)',padding:'5px 8px',borderRadius:'7px',border:'1px solid #26344d'});host.appendChild(el)}
function start(){buildPanels();hook();addLegend();load();setInterval(load,60000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();